name: Carthage
on: [pull_request]
jobs:
  check:
    runs-on: macos-12
    steps:
     - name: Select Xcode version
       run: |
        xcodebuild -version
        sudo xcode-select -s '/Applications/Xcode_13.4.app/Contents/Developer'
     - name: Initialize Cartfile
       run: |
        echo ${{ github.head_ref }}
        tee Cartfile <<<"github \"algolia/instantsearch-telemetry-native\" \"${{ github.head_ref }}\""
        carthage update --no-build
        cd ./Carthage/Checkouts/instantsearch-telemetry-native
        swift package generate-xcodeproj
        cd ../../..
        carthage build --use-xcframeworks --platform ios