# .github/workflows/runOnGitHub.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: runOnGitHub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  gradle:
    runs-on: macos-latest
    steps:
      - name: Checkout Swift Protobuf
        uses: actions/checkout@v2
        with:
          repository: apple/swift-protobuf
          ref: 1.18.0

      - name: Build Swift Protobuf
        run: swift build

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate protobuf specification
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: generate
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true